export const exercises = [
	{
		id: "head-turns",
		name: "Head Turns",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-15 reps",
		recommendedDuration: "20-30 seconds",
		description: "Gently stretches the neck muscles for mobility.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "shoulder-rolls",
		name: "Shoulder Rolls",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "5-15 reps",
		recommendedDuration: "20-30 seconds",
		description: "Relieves tension and improves shoulder flexibility.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "arm-circles",
		name: "Arm Circles",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-15 reps",
		recommendedDuration: "20-30 seconds",
		description: "Prepares shoulder joints for dynamic movement.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "overhead-stretch",
		name: "Overhead Stretch",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "1-2 reps",
		recommendedDuration: "10-20 seconds",
		description: "Improves upper body flexibility and posture.",
		duration: 20,
		repetitions: 2,
	},

	{
		id: "side-stretches",
		name: "Side Stretches",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "5-10 reps",
		recommendedDuration: "20-30 seconds",
		description: "Stretches the obliques and improves core flexibility.",
		duration: 30,
		repetitions: 10,
	},

	{
		id: "hip-rotation",
		name: "Hip Rotation",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-15 reps",
		recommendedDuration: "20-30 seconds",
		description: "Loosens up the hips for better mobility.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "knee-hugs",
		name: "Knee Hugs",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-12 reps",
		recommendedDuration: "20-30 seconds",
		description: "Improves hip mobility and balance.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "butt-kicks",
		name: "Butt Kicks",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "20-30 reps",
		recommendedDuration: "30-40 seconds",
		description: "Loosens hamstrings and activates glutes.",
		duration: 40,
		repetitions: 25,
	},

	{
		id: "walking-high-knees",
		name: "Walking High Knees",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-15 reps",
		recommendedDuration: "20-30 seconds",
		description: "Warms up the hip flexors and quads.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "jogging",
		name: "Jogging",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "1 rep",
		recommendedDuration: "2-3 minutes",
		description: "Increases heart rate and warms up muscles.",
		duration: 180,
		repetitions: 1,
	},

	{
		id: "lunges",
		name: "Lunges",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-12 reps",
		recommendedDuration: "30-40 seconds",
		description: "Strengthens legs and glutes.",
		duration: 40,
		repetitions: 12,
	},

	{
		id: "squat",
		name: "Squat",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-12 reps",
		recommendedDuration: "30-40 seconds",
		description: "Engages the lower body and core.",
		duration: 40,
		repetitions: 12,
	},

	{
		id: "jump-squat",
		name: "Jump Squat",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "8-12 reps",
		recommendedDuration: "20-30 seconds",
		description: "Improves explosiveness and leg strength.",
		duration: 30,
		repetitions: 10,
	},

	{
		id: "walking-lunges",
		name: "Walking Lunges",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-12 reps",
		recommendedDuration: "30-40 seconds",
		description: "Enhances balance and leg endurance.",
		duration: 40,
		repetitions: 12,
	},

	{
		id: "toe-touches",
		name: "Toe Touches",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "10-15 reps",
		recommendedDuration: "20-30 seconds",
		description:
			"Stand tall, feet shoulder-width apart. Slightly bend your knees, then reach toward your toes. Hold for 20 counts and return to start.",
		duration: 30,
		repetitions: 12,
	},

	{
		id: "jumping-jacks",
		name: "Jumping Jacks",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "20-30 reps",
		recommendedDuration: "30-40 seconds",
		description: "Boosts heart rate and warms up the entire body.",
		duration: 40,
		repetitions: 25,
	},

	{
		id: "defensive-slides",
		name: "Defensive Slides",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "2 sets",
		recommendedDuration: "15-30 seconds",
		description: "Improves lateral movement for defense.",
		duration: 30,
		repetitions: 2,
	},

	{
		id: "carioca",
		name: "Carioca",
		video: require("../../assets/videos/pushup.mp4"),
		image: require("../../assets/images/withballpreview.png"),
		recommendedRepetition: "2-3 sets",
		recommendedDuration: "20-30 seconds",
		description: "Enhances agility and coordination.",
		duration: 30,
		repetitions: 3,
	},
];

export default exercises;
